"use client";
import { useState, useMemo, useCallback } from "react";
import { parseRobustNumber, safeMultiply, safeAdd, safePower, safeDivide, safeSubtract } from "@/lib/utils/number";


import { GoalProgressChart } from "@/components/ui/goal-progress-chart";
import { AdsPlaceholder } from "@/components/ui/ads-placeholder";
import { CalculatorLayout } from "@/components/layout/calculator-layout";
import { EnhancedCalculatorForm, EnhancedCalculatorField, CalculatorResult } from "@/components/ui/enhanced-calculator-form";
import { useCurrency } from "@/contexts/currency-context";

interface InvestmentInputs {
  initialInvestment: number;
  monthlyContribution: number;
  annualReturnRate: number;
  years: number;
  goal: number;
}

const initialValues: InvestmentInputs = {
  initialInvestment: 10000,
  monthlyContribution: 500,
  annualReturnRate: 7,
  years: 20,
  goal: 0, // This will be dynamically set or user-defined
};

function calculateInvestment(inputs: InvestmentInputs) {
  const initial = parseRobustNumber(inputs.initialInvestment);
  const monthly = parseRobustNumber(inputs.monthlyContribution);
  const rate = parseRobustNumber(inputs.annualReturnRate);
  const years = parseRobustNumber(inputs.years);

  if (initial < 0) throw new Error("Initial investment cannot be negative.");
  if (monthly < 0) throw new Error("Monthly contribution cannot be negative.");
  if (rate < 0) throw new Error("Annual return rate cannot be negative.");
  if (years <= 0) throw new Error("Years must be greater than zero.");

  const n = years * 12; // Total months
  const r = safeDivide(safeDivide(rate, 12), 100); // Monthly rate

  // Future value of initial investment
  const fvInitial = safeMultiply(initial, safePower(safeAdd(1, r), n));

  // Future value of a series of monthly contributions (annuity)
  let fvMonthly = 0;
  if (!isFinite(r) || r === 0) { // Handle zero interest rate
    fvMonthly = safeMultiply(monthly, n);
  } else {
    fvMonthly = safeMultiply(monthly, safeDivide(safeSubtract(safePower(safeAdd(1, r), n), 1), r));
  }

  const totalFutureValue = safeAdd(fvInitial, fvMonthly);
  const totalContributions = safeAdd(initial, safeMultiply(monthly, n));
  const totalInterestEarned = safeSubtract(totalFutureValue, totalContributions);

  return {
    totalFutureValue,
    totalContributions,
    totalInterestEarned,
  };
}

export default function InvestmentCalculatorPage() {
  const [values, setValues] = useState<InvestmentInputs>(initialValues);
  const [loading, setLoading] = useState(false);
  const [calculationError, setCalculationError] = useState<string | undefined>(undefined);

  
  const { currency } = useCurrency();

  const investmentResults = useMemo(() => {
    setCalculationError(undefined);
    try {
      return calculateInvestment(values);
    } catch (err: any) {
      console.error("Investment calculation error:", err);
      setCalculationError(err.message || "An error occurred during calculation.");
      return null;
    }
  }, [values]);

  

  const fields: EnhancedCalculatorField[] = [
    {
      label: "Initial Investment",
      name: "initialInvestment",
      type: "number",
      placeholder: "10,000",
      unit: currency.symbol,
      min: 0,
      required: true,
    },
    {
      label: "Monthly Contribution",
      name: "monthlyContribution",
      type: "number",
      placeholder: "500",
      unit: currency.symbol,
      min: 0,
      required: true,
    },
    {
      label: "Annual Return Rate",
      name: "annualReturnRate",
      type: "percentage",
      placeholder: "7",
      min: 0,
      max: 50,
      step: 0.1,
      required: true,
    },
    {
      label: "Years",
      name: "years",
      type: "number",
      placeholder: "20",
      min: 1,
      max: 60,
      unit: "years",
      required: true,
    },
    {
      label: "Investment Goal",
      name: "goal",
      type: "number",
      placeholder: "1,000,000",
      unit: currency.symbol,
      min: 0,
      tooltip: "Set a target for your investment growth."
    },
  ];

  const results: CalculatorResult[] = useMemo(() => {
    if (!investmentResults) return [];

    return [
      {
        label: "Total Future Value",
        value: investmentResults.totalFutureValue,
        type: "currency",
        highlight: true,
        tooltip: "The total value of your investment at the end of the period.",
      },
      {
        label: "Total Contributions",
        value: investmentResults.totalContributions,
        type: "currency",
        tooltip: "The sum of your initial investment and all monthly contributions.",
      },
      {
        label: "Total Interest Earned",
        value: investmentResults.totalInterestEarned,
        type: "currency",
        tooltip: "The total interest or returns generated by your investment.",
      },
    ];
  }, [investmentResults, currency.symbol]);

  const handleChange = useCallback((name: string, value: any) => {
    setValues(prev => ({ ...prev, [name]: value }));
    setCalculationError(undefined);
  }, []);

  const handleCalculate = () => {
    setLoading(true);
    setCalculationError(undefined);
    setTimeout(() => setLoading(false), 400);
  };

  const sidebar = (
    <div className="space-y-4">
      <div className="card">
        <AdsPlaceholder position="sidebar" size="300x250" />
      </div>
      <div className="card">
        <h3 className="text-base font-semibold text-neutral-900 mb-4">Investment Tips</h3>
        <div className="space-y-2">
          <div className="flex items-start space-x-2">
            <span className="text-success-500 text-sm">✓</span>
            <p className="text-sm text-neutral-600">Start investing early to leverage compounding.</p>
          </div>
          <div className="flex items-start space-x-2">
            <span className="text-success-500 text-sm">✓</span>
            <p className="text-sm text-neutral-600">Regular contributions can significantly boost returns.</p>
          </div>
          <div className="flex items-start space-x-2">
            <span className="text-success-500 text-sm">✓</span>
            <p className="text-sm text-neutral-600">Diversify your portfolio to manage risk.</p>
          </div>
        </div>
      </div>
    </div>
  );

  return (
    <CalculatorLayout
      title="Investment Calculator"
      description="Estimate the future value of your investments with our comprehensive calculator. Plan your financial goals and see the power of compounding."
      sidebar={sidebar}
    >
      <EnhancedCalculatorForm
        title="Investment Details"
        description="Enter your investment details to project future growth."
        fields={fields}
        values={values}
        onChange={handleChange}
        onCalculate={handleCalculate}
        results={investmentResults ? results : []}
        loading={loading}
        error={calculationError}
        showComparison={false}
      />
      {investmentResults && values.goal > 0 && (
        <div className="mt-6 card p-6">
          <GoalProgressChart 
            currentValue={investmentResults.totalFutureValue} 
            goalValue={values.goal} 
            label="Investment Growth Progress" 
            unit={currency.symbol} 
          />
        </div>
      )
      }
    </CalculatorLayout>
  );
}